[buildPlans.iosevka-code]
family = "Iosevka Code"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-code.variants.design]
capital-g = "toothless-corner-serifless-hooked"
a = "double-storey-toothless-corner"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
i = "tailed-serifed"
l = "tailed-serifed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
u = "toothless-corner"
zero = "dotted"
eight = "crossing-asymmetric"
asterisk = "penta-low"
caret = "low"
brace = "straight"
ampersand = "flat-top"
dollar = "open"
cent = "open"

[buildPlans.iosevka-term]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-term.variants.design]
capital-g = "toothless-corner-serifless-hooked"
a = "double-storey-toothless-corner"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
i = "tailed-serifed"
l = "tailed-serifed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
u = "toothless-corner"
zero = "dotted"
eight = "crossing-asymmetric"
asterisk = "penta-low"
caret = "low"
brace = "straight"
ampersand = "flat-top"
dollar = "open"
cent = "open"

[buildPlans.iosevka-term-mono]
family = "Iosevka Term Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-term-mono.variants.design]
capital-g = "toothless-corner-serifless-hooked"
a = "double-storey-toothless-corner"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
i = "tailed-serifed"
l = "tailed-serifed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
u = "toothless-corner"
zero = "dotted"
eight = "crossing-asymmetric"
asterisk = "penta-low"
caret = "low"
brace = "straight"
ampersand = "flat-top"
dollar = "open"
cent = "open"
